# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordproject', '0007_auto_20160823_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordpair',
            name='original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_word', to='wordproject.WordRecord'),
        ),
        migrations.AlterField(
            model_name='wordpair',
            name='translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_word', to='wordproject.WordRecord'),
        ),
    ]
